//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public Nullable<bool> gender { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public Nullable<int> deparment_id { get; set; }
        public Nullable<int> role_id { get; set; }
        public string image { get; set; }
    }
}
